version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exercise_db
      MYSQL_USER: pau
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"